"""initial schema

Revision ID: 469d75f08cd1
Revises: 
Create Date: 2026-10-09 00:01:56.497426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469d75f08cd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosted_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'is_private', name='uq_zone_name_type')
    )
    op.create_index(op.f('ix_hosted_zones_name'), 'hosted_zones', ['name'], unique=False)
    op.create_index(op.f('ix_hosted_zones_zone_id'), 'hosted_zones', ['zone_id'], unique=True)
    op.create_table('mock_health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_check_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_health_checks_health_check_id'), 'mock_health_checks', ['health_check_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosted_zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('routing_policy', sa.String(length=16), nullable=False),
    sa.Column('set_identifier', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('failover', sa.String(length=10), nullable=True),
    sa.Column('geo_continent', sa.String(length=2), nullable=True),
    sa.Column('geo_country', sa.String(length=2), nullable=True),
    sa.Column('geo_subdivision', sa.String(length=3), nullable=True),
    sa.Column('alias_target', sa.String(length=255), nullable=True),
    sa.Column('alias_target_type', sa.String(length=20), nullable=True),
    sa.Column('alias_hosted_zone_id', sa.String(length=32), nullable=True),
    sa.Column('evaluate_target_health', sa.Boolean(), nullable=False),
    sa.Column('health_check_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['health_check_id'], ['mock_health_checks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hosted_zone_id', 'name', 'type', 'set_identifier', name='uq_record_identity')
    )
    op.create_index(op.f('ix_dns_records_type'), 'dns_records', ['type'], unique=False)
    op.create_index('ix_records_zone_name_type', 'dns_records', ['hosted_zone_id', 'name', 'type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('vpc_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosted_zone_id', sa.Integer(), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpc_associations_hosted_zone_id'), 'vpc_associations', ['hosted_zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpc_associations_hosted_zone_id'), table_name='vpc_associations')
    op.drop_table('vpc_associations')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_records_zone_name_type', table_name='dns_records')
    op.drop_index(op.f('ix_dns_records_type'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mock_health_checks_health_check_id'), table_name='mock_health_checks')
    op.drop_table('mock_health_checks')
    op.drop_index(op.f('ix_hosted_zones_zone_id'), table_name='hosted_zones')
    op.drop_index(op.f('ix_hosted_zones_name'), table_name='hosted_zones')
    op.drop_table('hosted_zones')
    # ### end Alembic commands ###
